version: "3.8"

services:

  backend:
    build: .
    ports:
      -  "5000:8080"
    depends_on:
      - postgres
      - redis
    environment:
      - DB_HOST=postgres
      - REDIS_HOST=redis

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abc123
      POSTGRES_DB: collab_editor
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"